// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Weterynarz.Basic.Enum;
using Weterynarz.Domain.ContextDb;

namespace Weterynarz.Domain.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180222175129_AddPriceToSummaryVisitTable")]
    partial class AddPriceToSummaryVisitTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Weterynarz.Domain.EntitiesDb.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("AnimalDesc");

                    b.Property<int>("AnimalTypeId");

                    b.Property<DateTime>("BirthDate");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("OwnerId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("AnimalTypeId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("Weterynarz.Domain.EntitiesDb.AnimalDisease", b =>
                {
                    b.Property<int>("AnimalId");

                    b.Property<int>("DiseaseId");

                    b.HasKey("AnimalId", "DiseaseId");

                    b.HasIndex("DiseaseId");

                    b.ToTable("AnimalDiseases");
                });

            modelBuilder.Entity("Weterynarz.Domain.EntitiesDb.AnimalMedicalExamination", b =>
                {
                    b.Property<int>("AnimalId");

                    b.Property<int>("MedicalExaminationId");

                    b.HasKey("AnimalId", "MedicalExaminationId");

                    b.HasIndex("MedicalExaminationId");

                    b.ToTable("AnimalMedicalExaminations");
                });

            modelBuilder.Entity("Weterynarz.Domain.EntitiesDb.AnimalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Description");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("AnimalTypes");
                });

            modelBuilder.Entity("Weterynarz.Domain.EntitiesDb.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<bool>("Active");

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("Deleted");

                    b.Property<string>("DoctorSpecialization");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("HouseNumber");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("Name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<string>("Surname");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<string>("ZipCode");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Weterynarz.Domain.EntitiesDb.Disease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Description");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Diseases");
                });

            modelBuilder.Entity("Weterynarz.Domain.EntitiesDb.DoctorGraphic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<DateTime>("AvailableFrom");

                    b.Property<DateTime>("AvailableTo");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("Deleted");

                    b.Property<string>("DoctorId")
                        .IsRequired();

                    b.Property<DateTime?>("ModificationDate");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorGraphics");
                });

            modelBuilder.Entity("Weterynarz.Domain.EntitiesDb.Graphic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("Deleted");

                    b.Property<int>("DoctorGraphicId");

                    b.Property<int>("FridayFrom");

                    b.Property<int>("FridayTo");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<int>("MondayFrom");

                    b.Property<int>("MondayTo");

                    b.Property<int>("SaturdayFrom");

                    b.Property<int>("SaturdayTo");

                    b.Property<int>("SundayFrom");

                    b.Property<int>("SundayTo");

                    b.Property<int>("ThursdayFrom");

                    b.Property<int>("ThursdayTo");

                    b.Property<int>("TuesdayFrom");

                    b.Property<int>("TuesdayTo");

                    b.Property<int>("WednesdayFrom");

                    b.Property<int>("WednesdayTo");

                    b.HasKey("Id");

                    b.HasIndex("DoctorGraphicId")
                        .IsUnique();

                    b.ToTable("Graphics");
                });

            modelBuilder.Entity("Weterynarz.Domain.EntitiesDb.MedicalExaminationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Description");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("MedicalExaminationTypes");
                });

            modelBuilder.Entity("Weterynarz.Domain.EntitiesDb.PriceList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("Deleted");

                    b.Property<int?>("MedicalExaminationId");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<decimal>("Price");

                    b.Property<int>("PriceListEntryType");

                    b.HasKey("Id");

                    b.HasIndex("MedicalExaminationId")
                        .IsUnique()
                        .HasFilter("[MedicalExaminationId] IS NOT NULL");

                    b.ToTable("PriceLists");
                });

            modelBuilder.Entity("Weterynarz.Domain.EntitiesDb.PriceSummaryVisit", b =>
                {
                    b.Property<int>("SummaryVisitId");

                    b.Property<int>("PriceListId");

                    b.HasKey("SummaryVisitId", "PriceListId");

                    b.HasIndex("PriceListId");

                    b.ToTable("PriceSummaryVisits");
                });

            modelBuilder.Entity("Weterynarz.Domain.EntitiesDb.SettingsContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Description");

                    b.Property<string>("Group");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("SettingsContent");
                });

            modelBuilder.Entity("Weterynarz.Domain.EntitiesDb.SummaryVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Drugs");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<decimal>("Price");

                    b.Property<int>("VisitId");

                    b.HasKey("Id");

                    b.HasIndex("VisitId")
                        .IsUnique();

                    b.ToTable("SummaryVisits");
                });

            modelBuilder.Entity("Weterynarz.Domain.EntitiesDb.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<int>("AnimalId");

                    b.Property<bool>("Approved");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Description");

                    b.Property<string>("DoctorId")
                        .IsRequired();

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("ReasonVisit");

                    b.Property<DateTime>("VisitDate");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("DoctorId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Weterynarz.Domain.EntitiesDb.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Weterynarz.Domain.EntitiesDb.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Weterynarz.Domain.EntitiesDb.ApplicationUser")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Weterynarz.Domain.EntitiesDb.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Weterynarz.Domain.EntitiesDb.Animal", b =>
                {
                    b.HasOne("Weterynarz.Domain.EntitiesDb.AnimalType", "AnimalType")
                        .WithMany("Animals")
                        .HasForeignKey("AnimalTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Weterynarz.Domain.EntitiesDb.ApplicationUser", "Owner")
                        .WithMany("Animals")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Weterynarz.Domain.EntitiesDb.AnimalDisease", b =>
                {
                    b.HasOne("Weterynarz.Domain.EntitiesDb.Animal", "Animal")
                        .WithMany("AnimalDiseases")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Weterynarz.Domain.EntitiesDb.Disease", "Disease")
                        .WithMany("AnimalDiseases")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Weterynarz.Domain.EntitiesDb.AnimalMedicalExamination", b =>
                {
                    b.HasOne("Weterynarz.Domain.EntitiesDb.Animal", "Animal")
                        .WithMany("AnimalMedicalExaminations")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Weterynarz.Domain.EntitiesDb.MedicalExaminationType", "MedicalExamination")
                        .WithMany("AnimalMedicalExaminations")
                        .HasForeignKey("MedicalExaminationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Weterynarz.Domain.EntitiesDb.DoctorGraphic", b =>
                {
                    b.HasOne("Weterynarz.Domain.EntitiesDb.ApplicationUser", "Doctor")
                        .WithMany("DoctorGraphics")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Weterynarz.Domain.EntitiesDb.Graphic", b =>
                {
                    b.HasOne("Weterynarz.Domain.EntitiesDb.DoctorGraphic", "DoctorGraphic")
                        .WithOne("Graphic")
                        .HasForeignKey("Weterynarz.Domain.EntitiesDb.Graphic", "DoctorGraphicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Weterynarz.Domain.EntitiesDb.PriceList", b =>
                {
                    b.HasOne("Weterynarz.Domain.EntitiesDb.MedicalExaminationType", "MedicalExamination")
                        .WithOne("Price")
                        .HasForeignKey("Weterynarz.Domain.EntitiesDb.PriceList", "MedicalExaminationId");
                });

            modelBuilder.Entity("Weterynarz.Domain.EntitiesDb.PriceSummaryVisit", b =>
                {
                    b.HasOne("Weterynarz.Domain.EntitiesDb.PriceList", "PriceList")
                        .WithMany("PriceSummaryVisit")
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Weterynarz.Domain.EntitiesDb.SummaryVisit", "SummaryVisit")
                        .WithMany("PriceSummaryVisit")
                        .HasForeignKey("SummaryVisitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Weterynarz.Domain.EntitiesDb.SummaryVisit", b =>
                {
                    b.HasOne("Weterynarz.Domain.EntitiesDb.Visit", "Visit")
                        .WithOne("SummaryVisit")
                        .HasForeignKey("Weterynarz.Domain.EntitiesDb.SummaryVisit", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Weterynarz.Domain.EntitiesDb.Visit", b =>
                {
                    b.HasOne("Weterynarz.Domain.EntitiesDb.Animal", "Animal")
                        .WithMany("Visits")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Weterynarz.Domain.EntitiesDb.ApplicationUser", "Doctor")
                        .WithMany("Visits")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
