-- dodanie ról
INSERT INTO [dbo].[AspNetRoles] ([Id], [ConcurrencyStamp], [Name], [NormalizedName]) VALUES (N'admin', N'660c22e4-ad3f-4038-92e2-26e5c21f30e1', N'admin', N'ADMIN')
INSERT INTO [dbo].[AspNetRoles] ([Id], [ConcurrencyStamp], [Name], [NormalizedName]) VALUES (N'client', N'b99a27cc-22e1-4176-9121-2fc578dc5e9c', N'client', N'CLIENT')
INSERT INTO [dbo].[AspNetRoles] ([Id], [ConcurrencyStamp], [Name], [NormalizedName]) VALUES (N'doctor', N'1a6b756b-3492-4f63-870e-a67520dbf1cb', N'doctor', N'DOCTOR')
INSERT INTO [dbo].[AspNetRoles] ([Id], [ConcurrencyStamp], [Name], [NormalizedName]) VALUES (N'worker', N'8ceda684-234f-45cb-bf82-ef73003d83fb', N'worker', N'WORKER')

-- dodanie połączeń użytkownik-rola
INSERT INTO [dbo].[AspNetUserRoles] ([UserId], [RoleId]) VALUES (N'e536de1b-33df-4e1c-b214-bc776e3d7dc5', N'admin')

-- dodanie admina
INSERT INTO [dbo].[AspNetUsers] ([Id], [AccessFailedCount], [ConcurrencyStamp], [Email], [EmailConfirmed], [LockoutEnabled], [LockoutEnd], [NormalizedEmail], [NormalizedUserName], [PasswordHash], [PhoneNumber], [PhoneNumberConfirmed], [SecurityStamp], [TwoFactorEnabled], [UserName], [Address], [City], [HouseNumber], [Name], [Surname], [ZipCode], [Active], [CreationDate], [Deleted], [ModificationDate]) VALUES (N'e536de1b-33df-4e1c-b214-bc776e3d7dc5', 0, N'5e998d46-f1c0-47ce-930a-5818f05b30e8', N'admin@admin.pl', 1, 1, NULL, N'ADMIN@ADMIN.PL', N'ADMIN', N'AQAAAAEAACcQAAAAEJSwleRig1rwiawXYIcLVz6aWqO1+EPbqdj2DnLtRYHfF4Cd/cGXiNonqRfpeh6z8g==', NULL, 0, N'6439a498-7ead-419e-8200-660bbff91fe4', 0, N'admin', NULL, NULL, NULL, N'admin', N'admin', NULL, 1, N'2017-12-18 00:00:00', 0, N'0001-01-01 00:00:00')

-- dodanie ustawień treści
SET IDENTITY_INSERT [dbo].[SettingsContent] ON
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (1, 1, N'2018-01-03 00:00:00', 0, NULL, N'Sekcja nagłówek', N'2018-01-06 16:15:06', N'Tytuł', N'Całodobowa klinika weterynaryjna', N'pageTitle')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (2, 1, N'2018-01-03 00:00:00', 0, NULL, N'Sekcja nagłówek', N'2018-01-03 22:53:37', N'Nadtytuł', N'Witaj !', N'pageSubTitle')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (3, 1, N'2018-01-03 00:00:00', 0, NULL, N'Sekcja nagłówek', NULL, N'Tekst przycisku', N'Więcej', N'pageTitleButton')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (4, 1, N'2018-01-08 17:29:19', 0, NULL, N'Sekcja o nas', NULL, N'Paragraf 1 - tytuł', N'Początki', N'aboutUsParag1Title')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (5, 1, N'2018-01-08 17:29:19', 0, NULL, N'Sekcja o nas', NULL, N'Paragraf 1 - tekst', N'Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu.', N'aboutUsParag1Text')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (6, 1, N'2018-01-08 17:29:19', 0, NULL, N'Sekcja o nas', NULL, N'Paragraf 2 - tytuł', N'Nasza oferta', N'aboutUsParag2Title')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (7, 1, N'2018-01-08 17:29:19', 0, NULL, N'Sekcja o nas', NULL, N'Paragraf 2 - tekst', N'Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu.', N'aboutUsParag2Text')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (8, 1, N'2018-01-08 17:29:19', 0, NULL, N'Sekcja o nas', NULL, N'Paragraf 3 - tytuł', N'Zespół', N'aboutUsParag3Title')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (9, 1, N'2018-01-08 17:29:19', 0, NULL, N'Sekcja o nas', NULL, N'Paragraf 3 - tekst', N'Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu.', N'aboutUsParag3Text')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (10, 1, N'2018-01-08 17:30:36', 0, NULL, N'Sekcja o nas', N'2018-01-08 17:34:58', N'Tytuł', N'O nas', N'aboutUsTitle')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (11, 1, N'2018-01-08 17:30:36', 0, NULL, N'Sekcja o nas', NULL, N'Podtytuł', N'Potrafimy wszystko i jeszcze więcej', N'aboutUsSubTitle')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (12, 1, N'2018-01-08 17:36:52', 0, NULL, N'Sekcja oferta', NULL, N'Tytuł', N'Oferta', N'offerTitle')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (13, 1, N'2018-01-08 17:36:52', 0, NULL, N'Sekcja oferta', NULL, N'Podtytuł', N'Zawsze dajemy z siebie 150%', N'offerSubTitle')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (14, 1, N'2018-01-08 17:44:26', 0, NULL, N'Sekcja oferta', NULL, N'Paragraf 1 - tytuł', N'Profilaktyka', N'offerParag1Title')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (15, 1, N'2018-01-08 17:44:26', 0, NULL, N'Sekcja oferta', NULL, N'Paragraf 1 - tekst', N'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.', N'offerParag1Text')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (16, 1, N'2018-01-08 17:44:26', 0, NULL, N'Sekcja oferta', NULL, N'Paragraf 2 - tytuł', N'Badanie RTG', N'offerParag2Title')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (17, 1, N'2018-01-08 17:44:26', 0, NULL, N'Sekcja oferta', NULL, N'Paragraf 2 - tekst', N'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.', N'offerParag2Text')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (18, 1, N'2018-01-08 17:44:26', 0, NULL, N'Sekcja oferta', NULL, N'Paragraf 3 - tytuł', N'Hospitalizacja', N'offerParag3Title')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (19, 1, N'2018-01-08 17:44:26', 0, NULL, N'Sekcja oferta', NULL, N'Paragraf 3 - tekst', N'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.', N'offerParag3Text')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (20, 1, N'2018-01-08 17:44:26', 0, NULL, N'Sekcja oferta', NULL, N'Paragraf 4 - tytuł', N'Diagnostyka', N'offerParag4Title')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (21, 1, N'2018-01-08 17:44:26', 0, NULL, N'Sekcja oferta', NULL, N'Paragraf 4 - tekst', N'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.', N'offerParag4Text')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (22, 1, N'2018-01-08 17:44:26', 0, NULL, N'Sekcja oferta', NULL, N'Paragraf 5 - tytuł', N'Badania kardiologiczne', N'offerParag5Title')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (23, 1, N'2018-01-08 17:44:26', 0, NULL, N'Sekcja oferta', NULL, N'Paragraf 5 - tekst', N'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.', N'offerParag5Text')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (24, 1, N'2018-01-08 17:44:26', 0, NULL, N'Sekcja oferta', NULL, N'Paragraf 6 - tytuł', N'Profilaktyka', N'offerParag6Title')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (25, 1, N'2018-01-08 17:44:26', 0, NULL, N'Sekcja oferta', NULL, N'Paragraf 6 - tekst', N'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.', N'offerParag6Text')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (26, 1, N'2018-01-08 17:52:44', 0, NULL, N'Sekcja nasz zespół', NULL, N'Tytuł', N'Nasz zespół', N'teamTitle')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (27, 1, N'2018-01-08 17:52:44', 0, NULL, N'Sekcja nasz zespół', NULL, N'Podtytuł', N'Mamy najlepszych specjalistów', N'teamSubTitle')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (28, 1, N'2018-01-08 17:52:44', 0, NULL, N'Sekcja kontakt', NULL, N'Tytuł', N'Kontakt', N'contactTitle')
INSERT INTO [dbo].[SettingsContent] ([Id], [Active], [CreationDate], [Deleted], [Description], [Group], [ModificationDate], [Name], [Value], [Code]) VALUES (29, 1, N'2018-01-08 17:52:44', 0, NULL, N'Sekcja kontakt', NULL, N'Podtytuł', N'Odpowiemy na każdą wiadomość wiadomość najszybciej jak potrafimy', N'contactSubTitle')
SET IDENTITY_INSERT [dbo].[SettingsContent] OFF

