//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weterynarz.Basic.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć członka, edytuj plik .ResX, a następnie ponownie uruchom ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResAdmin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResAdmin() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weterynarz.Basic.Resources.ResAdmin", typeof(ResAdmin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd podczas potwierdzania adresu e-mail.
        /// </summary>
        public static string account_errorConfirmedEmail {
            get {
                return ResourceManager.GetString("account_errorConfirmedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Niepoprawny link.
        /// </summary>
        public static string account_errorIncorrectLink {
            get {
                return ResourceManager.GetString("account_errorIncorrectLink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa użytkownika nie może być pusta.
        /// </summary>
        public static string account_errorUserNameIsNull {
            get {
                return ResourceManager.GetString("account_errorUserNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Użytkownik nie istnieje.
        /// </summary>
        public static string account_errorUserNotExists {
            get {
                return ResourceManager.GetString("account_errorUserNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Adres e-mail został potwierdzony.
        /// </summary>
        public static string account_successConfirmedEmail {
            get {
                return ResourceManager.GetString("account_successConfirmedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj użytkownika.
        /// </summary>
        public static string accountCreateView_header {
            get {
                return ResourceManager.GetString("accountCreateView_header", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edytuj użytkownika.
        /// </summary>
        public static string accountEditView_header {
            get {
                return ResourceManager.GetString("accountEditView_header", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rejestracja.
        /// </summary>
        public static string accountRegisterView_header {
            get {
                return ResourceManager.GetString("accountRegisterView_header", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lista użytkowników.
        /// </summary>
        public static string accountsListViewModel_list {
            get {
                return ResourceManager.GetString("accountsListViewModel_list", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lista lekarzy.
        /// </summary>
        public static string accountsListViewModel_listDoctors {
            get {
                return ResourceManager.GetString("accountsListViewModel_listDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Adres.
        /// </summary>
        public static string accountsManageViewModel_address {
            get {
                return ResourceManager.GetString("accountsManageViewModel_address", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Miasto.
        /// </summary>
        public static string accountsManageViewModel_city {
            get {
                return ResourceManager.GetString("accountsManageViewModel_city", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Potwierdź hasło.
        /// </summary>
        public static string accountsManageViewModel_confirmPassword {
            get {
                return ResourceManager.GetString("accountsManageViewModel_confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Adres e-mail.
        /// </summary>
        public static string accountsManageViewModel_email {
            get {
                return ResourceManager.GetString("accountsManageViewModel_email", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Numer domu.
        /// </summary>
        public static string accountsManageViewModel_houseNumber {
            get {
                return ResourceManager.GetString("accountsManageViewModel_houseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lista użytkowników.
        /// </summary>
        public static string accountsManageViewModel_list {
            get {
                return ResourceManager.GetString("accountsManageViewModel_list", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Imię.
        /// </summary>
        public static string accountsManageViewModel_name {
            get {
                return ResourceManager.GetString("accountsManageViewModel_name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hasło.
        /// </summary>
        public static string accountsManageViewModel_password {
            get {
                return ResourceManager.GetString("accountsManageViewModel_password", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwisko.
        /// </summary>
        public static string accountsManageViewModel_surname {
            get {
                return ResourceManager.GetString("accountsManageViewModel_surname", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa użytkownika.
        /// </summary>
        public static string accountsManageViewModel_userName {
            get {
                return ResourceManager.GetString("accountsManageViewModel_userName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kod pocztowy.
        /// </summary>
        public static string accountsManageViewModel_zipCode {
            get {
                return ResourceManager.GetString("accountsManageViewModel_zipCode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj zwierzę.
        /// </summary>
        public static string animalsCreateView_headerForm {
            get {
                return ResourceManager.GetString("animalsCreateView_headerForm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edytuj zwierzę.
        /// </summary>
        public static string animalsEditView_headerForm {
            get {
                return ResourceManager.GetString("animalsEditView_headerForm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lista zwierząt.
        /// </summary>
        public static string animalsIndex_listTypes {
            get {
                return ResourceManager.GetString("animalsIndex_listTypes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj typ zwierzęcia.
        /// </summary>
        public static string animalTypesCreateView_headerForm {
            get {
                return ResourceManager.GetString("animalTypesCreateView_headerForm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edytuj typ zwierzęcia.
        /// </summary>
        public static string animalTypesEditView_headerForm {
            get {
                return ResourceManager.GetString("animalTypesEditView_headerForm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Typy zwierząt.
        /// </summary>
        public static string animalTypesIndex_listTypes {
            get {
                return ResourceManager.GetString("animalTypesIndex_listTypes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj.
        /// </summary>
        public static string button_add {
            get {
                return ResourceManager.GetString("button_add", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj chorobę.
        /// </summary>
        public static string diseasesCreateView_headerForm {
            get {
                return ResourceManager.GetString("diseasesCreateView_headerForm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edytuj chorobę.
        /// </summary>
        public static string diseasesEditView_headerForm {
            get {
                return ResourceManager.GetString("diseasesEditView_headerForm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choroby.
        /// </summary>
        public static string diseasesIndex_list {
            get {
                return ResourceManager.GetString("diseasesIndex_list", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił problem z dodaniem grafiku lekarza.
        /// </summary>
        public static string doctorGraphic_errorAddGraphic {
            get {
                return ResourceManager.GetString("doctorGraphic_errorAddGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Coś poszło nie tak przy usuwaniu grafiki.
        /// </summary>
        public static string doctorGraphic_errorDeleteGraphic {
            get {
                return ResourceManager.GetString("doctorGraphic_errorDeleteGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie wiadomo o jakiego lekarza chodzi.
        /// </summary>
        public static string doctorGraphic_errorDoctorNotFound {
            get {
                return ResourceManager.GetString("doctorGraphic_errorDoctorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się pobrać grafiku lekarza.
        /// </summary>
        public static string doctorGraphic_errorGraphicNotFound {
            get {
                return ResourceManager.GetString("doctorGraphic_errorGraphicNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił problem z zapisem grafiku lekarza.
        /// </summary>
        public static string doctorGraphic_errorSaveGraphic {
            get {
                return ResourceManager.GetString("doctorGraphic_errorSaveGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Grafik został dodany.
        /// </summary>
        public static string doctorGraphic_successAddGraphic {
            get {
                return ResourceManager.GetString("doctorGraphic_successAddGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pomyślnie usunięto grafik.
        /// </summary>
        public static string doctorGraphic_successDeleteGraphic {
            get {
                return ResourceManager.GetString("doctorGraphic_successDeleteGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Grafik został zapisany.
        /// </summary>
        public static string doctorGraphic_successSaveGraphic {
            get {
                return ResourceManager.GetString("doctorGraphic_successSaveGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wszystkie grafiki lekarza.
        /// </summary>
        public static string doctorGraphicsAllGraphics_listGraphics {
            get {
                return ResourceManager.GetString("doctorGraphicsAllGraphics_listGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodawanie grafiku.
        /// </summary>
        public static string doctorGraphicsCreateGraphicView_headerForm {
            get {
                return ResourceManager.GetString("doctorGraphicsCreateGraphicView_headerForm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zwierzęta.
        /// </summary>
        public static string leftNavbar_animals {
            get {
                return ResourceManager.GetString("leftNavbar_animals", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gatunki zwierząt.
        /// </summary>
        public static string leftNavbar_animalTypes {
            get {
                return ResourceManager.GetString("leftNavbar_animalTypes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Treści strony głównej.
        /// </summary>
        public static string leftNavbar_contentHomePage {
            get {
                return ResourceManager.GetString("leftNavbar_contentHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Słowniki.
        /// </summary>
        public static string leftNavbar_dictionares {
            get {
                return ResourceManager.GetString("leftNavbar_dictionares", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choroby.
        /// </summary>
        public static string leftNavbar_diseases {
            get {
                return ResourceManager.GetString("leftNavbar_diseases", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lekarze.
        /// </summary>
        public static string leftNavbar_doctors {
            get {
                return ResourceManager.GetString("leftNavbar_doctors", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Strona główna.
        /// </summary>
        public static string leftNavbar_home {
            get {
                return ResourceManager.GetString("leftNavbar_home", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Typy badań.
        /// </summary>
        public static string leftNavbar_medicalExaminationTypes {
            get {
                return ResourceManager.GetString("leftNavbar_medicalExaminationTypes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ustawienia.
        /// </summary>
        public static string leftNavbar_settings {
            get {
                return ResourceManager.GetString("leftNavbar_settings", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Użytkownicy systemu.
        /// </summary>
        public static string leftNavbar_users {
            get {
                return ResourceManager.GetString("leftNavbar_users", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wizyty.
        /// </summary>
        public static string leftNavbar_visits {
            get {
                return ResourceManager.GetString("leftNavbar_visits", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak elementów.
        /// </summary>
        public static string list_emptyRecords {
            get {
                return ResourceManager.GetString("list_emptyRecords", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hasło.
        /// </summary>
        public static string loginViewModel_password {
            get {
                return ResourceManager.GetString("loginViewModel_password", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapamiętaj mnie.
        /// </summary>
        public static string loginViewModel_rememberMe {
            get {
                return ResourceManager.GetString("loginViewModel_rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa użytkownika.
        /// </summary>
        public static string loginViewModel_userName {
            get {
                return ResourceManager.GetString("loginViewModel_userName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Opis.
        /// </summary>
        public static string manageViewModel_description {
            get {
                return ResourceManager.GetString("manageViewModel_description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa.
        /// </summary>
        public static string manageViewModel_name {
            get {
                return ResourceManager.GetString("manageViewModel_name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj typ badania.
        /// </summary>
        public static string medicalExaminationTypesCreateView_headerForm {
            get {
                return ResourceManager.GetString("medicalExaminationTypesCreateView_headerForm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edytuj typ badania.
        /// </summary>
        public static string medicalExaminationTypesEditView_headerForm {
            get {
                return ResourceManager.GetString("medicalExaminationTypesEditView_headerForm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Typy badań.
        /// </summary>
        public static string medicalExaminationTypesIndex_listTypes {
            get {
                return ResourceManager.GetString("medicalExaminationTypesIndex_listTypes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Treści strony głównej.
        /// </summary>
        public static string settingsContent_listContent {
            get {
                return ResourceManager.GetString("settingsContent_listContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edytuj treść.
        /// </summary>
        public static string settingsContentEditView_headerForm {
            get {
                return ResourceManager.GetString("settingsContentEditView_headerForm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Opcje.
        /// </summary>
        public static string text_options {
            get {
                return ResourceManager.GetString("text_options", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Konto zostało utworzone lecz proszę potwierdzić jeszcze założenie konta.
        /// </summary>
        public static string user_successRegister {
            get {
                return ResourceManager.GetString("user_successRegister", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj użytkownika.
        /// </summary>
        public static string userCreateView_header {
            get {
                return ResourceManager.GetString("userCreateView_header", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rejestracja.
        /// </summary>
        public static string userRegisterView_header {
            get {
                return ResourceManager.GetString("userRegisterView_header", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Administrator.
        /// </summary>
        public static string userRoles_admin {
            get {
                return ResourceManager.GetString("userRoles_admin", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Klient.
        /// </summary>
        public static string userRoles_client {
            get {
                return ResourceManager.GetString("userRoles_client", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lekarz.
        /// </summary>
        public static string userRoles_doctor {
            get {
                return ResourceManager.GetString("userRoles_doctor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pracownik.
        /// </summary>
        public static string userRoles_worker {
            get {
                return ResourceManager.GetString("userRoles_worker", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Adres.
        /// </summary>
        public static string usersManageViewModel_address {
            get {
                return ResourceManager.GetString("usersManageViewModel_address", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Miejscowość.
        /// </summary>
        public static string usersManageViewModel_city {
            get {
                return ResourceManager.GetString("usersManageViewModel_city", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Powtórz hasło.
        /// </summary>
        public static string usersManageViewModel_confirmPassword {
            get {
                return ResourceManager.GetString("usersManageViewModel_confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu E-mail.
        /// </summary>
        public static string usersManageViewModel_email {
            get {
                return ResourceManager.GetString("usersManageViewModel_email", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nr domu.
        /// </summary>
        public static string usersManageViewModel_houseNumber {
            get {
                return ResourceManager.GetString("usersManageViewModel_houseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Imię.
        /// </summary>
        public static string usersManageViewModel_name {
            get {
                return ResourceManager.GetString("usersManageViewModel_name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hasło.
        /// </summary>
        public static string usersManageViewModel_password {
            get {
                return ResourceManager.GetString("usersManageViewModel_password", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Specjalizacja.
        /// </summary>
        public static string usersManageViewModel_specialization {
            get {
                return ResourceManager.GetString("usersManageViewModel_specialization", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwisko.
        /// </summary>
        public static string usersManageViewModel_surname {
            get {
                return ResourceManager.GetString("usersManageViewModel_surname", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa użytkownika.
        /// </summary>
        public static string usersManageViewModel_userName {
            get {
                return ResourceManager.GetString("usersManageViewModel_userName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kod pocztowy.
        /// </summary>
        public static string usersManageViewModel_zipCode {
            get {
                return ResourceManager.GetString("usersManageViewModel_zipCode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj wizytę.
        /// </summary>
        public static string visitCreateView_headerForm {
            get {
                return ResourceManager.GetString("visitCreateView_headerForm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edytuj wizytę.
        /// </summary>
        public static string visitEditView_headerForm {
            get {
                return ResourceManager.GetString("visitEditView_headerForm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Do tej wizyty nie jest przypisane żadne zwierzę.
        /// </summary>
        public static string visitRepo_animalNotFoundException {
            get {
                return ResourceManager.GetString("visitRepo_animalNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lista wizyt.
        /// </summary>
        public static string visitsIndex_list {
            get {
                return ResourceManager.GetString("visitsIndex_list", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj podsumowanie.
        /// </summary>
        public static string visitSummaryCreateView_headerForm {
            get {
                return ResourceManager.GetString("visitSummaryCreateView_headerForm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zwierze.
        /// </summary>
        public static string visitSummaryIndexView_animal {
            get {
                return ResourceManager.GetString("visitSummaryIndexView_animal", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Opis wizyty.
        /// </summary>
        public static string visitSummaryIndexView_description {
            get {
                return ResourceManager.GetString("visitSummaryIndexView_description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choroby.
        /// </summary>
        public static string visitSummaryIndexView_diseases {
            get {
                return ResourceManager.GetString("visitSummaryIndexView_diseases", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Leki.
        /// </summary>
        public static string visitSummaryIndexView_drugs {
            get {
                return ResourceManager.GetString("visitSummaryIndexView_drugs", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Badania.
        /// </summary>
        public static string visitSummaryIndexView_medicalExaminations {
            get {
                return ResourceManager.GetString("visitSummaryIndexView_medicalExaminations", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Właściciel zwierzęcia.
        /// </summary>
        public static string visitSummaryIndexView_owner {
            get {
                return ResourceManager.GetString("visitSummaryIndexView_owner", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data wizyty.
        /// </summary>
        public static string visitSummaryIndexView_visitDate {
            get {
                return ResourceManager.GetString("visitSummaryIndexView_visitDate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono wizyty o podanym Id.
        /// </summary>
        public static string visitSummaryRepo_visitNotFoundException {
            get {
                return ResourceManager.GetString("visitSummaryRepo_visitNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podsumowanie wizyty.
        /// </summary>
        public static string visitSummaryView_headerForm {
            get {
                return ResourceManager.GetString("visitSummaryView_headerForm", resourceCulture);
            }
        }
    }
}
