//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weterynarz.Basic.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć członka, edytuj plik .ResX, a następnie ponownie uruchom ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResAdmin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResAdmin() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weterynarz.Basic.Resources.ResAdmin", typeof(ResAdmin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj użytkownika.
        /// </summary>
        public static string accountCreateView_header {
            get {
                return ResourceManager.GetString("accountCreateView_header", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edytuj użytkownika.
        /// </summary>
        public static string accountEditView_header {
            get {
                return ResourceManager.GetString("accountEditView_header", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lista użytkowników.
        /// </summary>
        public static string accountsListViewModel_list {
            get {
                return ResourceManager.GetString("accountsListViewModel_list", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Adres.
        /// </summary>
        public static string accountsManageViewModel_address {
            get {
                return ResourceManager.GetString("accountsManageViewModel_address", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Miasto.
        /// </summary>
        public static string accountsManageViewModel_city {
            get {
                return ResourceManager.GetString("accountsManageViewModel_city", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Potwierdź hasło.
        /// </summary>
        public static string accountsManageViewModel_confirmPassword {
            get {
                return ResourceManager.GetString("accountsManageViewModel_confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Adres e-mail.
        /// </summary>
        public static string accountsManageViewModel_email {
            get {
                return ResourceManager.GetString("accountsManageViewModel_email", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Numer domu.
        /// </summary>
        public static string accountsManageViewModel_houseNumber {
            get {
                return ResourceManager.GetString("accountsManageViewModel_houseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lista użytkowników.
        /// </summary>
        public static string accountsManageViewModel_list {
            get {
                return ResourceManager.GetString("accountsManageViewModel_list", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Imię.
        /// </summary>
        public static string accountsManageViewModel_name {
            get {
                return ResourceManager.GetString("accountsManageViewModel_name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hasło.
        /// </summary>
        public static string accountsManageViewModel_password {
            get {
                return ResourceManager.GetString("accountsManageViewModel_password", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwisko.
        /// </summary>
        public static string accountsManageViewModel_surname {
            get {
                return ResourceManager.GetString("accountsManageViewModel_surname", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa użytkownika.
        /// </summary>
        public static string accountsManageViewModel_userName {
            get {
                return ResourceManager.GetString("accountsManageViewModel_userName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kod pocztowy.
        /// </summary>
        public static string accountsManageViewModel_zipCode {
            get {
                return ResourceManager.GetString("accountsManageViewModel_zipCode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj typ zwierzęcia.
        /// </summary>
        public static string animalTypesCreateView_headerForm {
            get {
                return ResourceManager.GetString("animalTypesCreateView_headerForm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edytuj typ zwierzęcia.
        /// </summary>
        public static string animalTypesEditView_headerForm {
            get {
                return ResourceManager.GetString("animalTypesEditView_headerForm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Typy zwierząt.
        /// </summary>
        public static string animalTypesIndex_listTypes {
            get {
                return ResourceManager.GetString("animalTypesIndex_listTypes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj.
        /// </summary>
        public static string button_add {
            get {
                return ResourceManager.GetString("button_add", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gatunki zwierząt.
        /// </summary>
        public static string leftNavbar_animalTypes {
            get {
                return ResourceManager.GetString("leftNavbar_animalTypes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Słowniki.
        /// </summary>
        public static string leftNavbar_dictionares {
            get {
                return ResourceManager.GetString("leftNavbar_dictionares", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Strona główna.
        /// </summary>
        public static string leftNavbar_home {
            get {
                return ResourceManager.GetString("leftNavbar_home", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Typy badań.
        /// </summary>
        public static string leftNavbar_medicalExaminationTypes {
            get {
                return ResourceManager.GetString("leftNavbar_medicalExaminationTypes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Użytkownicy systemu.
        /// </summary>
        public static string leftNavbar_users {
            get {
                return ResourceManager.GetString("leftNavbar_users", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak elementów.
        /// </summary>
        public static string list_emptyRecords {
            get {
                return ResourceManager.GetString("list_emptyRecords", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hasło.
        /// </summary>
        public static string loginViewModel_password {
            get {
                return ResourceManager.GetString("loginViewModel_password", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapamiętaj mnie.
        /// </summary>
        public static string loginViewModel_rememberMe {
            get {
                return ResourceManager.GetString("loginViewModel_rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa użytkownika.
        /// </summary>
        public static string loginViewModel_userName {
            get {
                return ResourceManager.GetString("loginViewModel_userName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Opis.
        /// </summary>
        public static string manageViewModel_description {
            get {
                return ResourceManager.GetString("manageViewModel_description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa.
        /// </summary>
        public static string manageViewModel_name {
            get {
                return ResourceManager.GetString("manageViewModel_name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj typ badania.
        /// </summary>
        public static string medicalExaminationTypesCreateView_headerForm {
            get {
                return ResourceManager.GetString("medicalExaminationTypesCreateView_headerForm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edytuj typ badania.
        /// </summary>
        public static string medicalExaminationTypesEditView_headerForm {
            get {
                return ResourceManager.GetString("medicalExaminationTypesEditView_headerForm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Typy badań.
        /// </summary>
        public static string medicalExaminationTypesIndex_listTypes {
            get {
                return ResourceManager.GetString("medicalExaminationTypesIndex_listTypes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Opcje.
        /// </summary>
        public static string text_options {
            get {
                return ResourceManager.GetString("text_options", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Administrator.
        /// </summary>
        public static string userRoles_admin {
            get {
                return ResourceManager.GetString("userRoles_admin", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Klient.
        /// </summary>
        public static string userRoles_client {
            get {
                return ResourceManager.GetString("userRoles_client", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lekarz.
        /// </summary>
        public static string userRoles_doctor {
            get {
                return ResourceManager.GetString("userRoles_doctor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pracownik.
        /// </summary>
        public static string userRoles_worker {
            get {
                return ResourceManager.GetString("userRoles_worker", resourceCulture);
            }
        }
    }
}
